#!/system/bin/sh
# KTSR™ by pedro (pedrozzz0 @ GitHub)
# Thanks: tytydraco @ Github
# If you wanna use it as part of your project, please maintain the credits to it respective's author(s).
modpath="/data/adb/modules/KTSR"

[[ "$1" == "--debug" ]] || [[ "$1" == "-d" ]] && set -x

# Load libraries
source "$modpath/libs/libcommon.sh"

glog="/data/media/0/ktsr/game_opt.log"
cpid="/data/media/0/ktsr/pid"

log_g() {
	echo "[$(date +%T)]: [*] $1" >>"$glog"
}

log_i() { echo "$1" >> "$glog"; }

gameopt() {
	rebuild_ps_cache
	pin_thread_on_custom "dts.freefireth|league.wildrift|game.kwgt|tencent.lolm|league.wildrift|tmgp.sgame|obile.legends|ncent.tmgp.cf|cent.tmgp.cod|GenshinImpact" "Apollo-Source|Apollo-File|UnityMain|UnityPreload" "80"
	pin_thread_on_custom "dts.freefireth|league.wildrift|game.kwgt|tencent.lolm|league.wildrift|tmgp.sgame|obile.legends|ncent.tmgp.cf|cent.tmgp.cod|GenshinImpact" "NativeThread|Thread-|UnityGfx|UnityMultiRende|ReadManager|UnityChoreograp|Worker Thread" "70"
	pin_thread_on_pwr "dts.freefireth|league.wildrift|game.kwgt|tencent.lolm|league.wildrift|tmgp.sgame|obile.legends|ncent.tmgp.cf|cent.tmgp.cod|GenshinImpact" "Audio|MIHOYO_NETWORK|tp_schedule|NDK Media|GVoice|FMOD mixer|FMOD stream|ff_read"
	pin_thread_on_custom "tmgp.pubgmhd|tencent.ig|ease.jddsaef|etease.g93na|ease.g93natw|legendsmobilefps|legendsmobile|pubg.imobile|tease.mrzhna|hotta.|dw.h5yvzr.yt" "Thread-" "80"
	pin_thread_on_custom "tmgp.pubgmhd|tencent.ig|legendsmobilefps|legendsmobile|pubg.imobile|tease.mrzhna|hotta.|dw.h5yvzr.yt" "RenderThread|TaskGraphNP|RHIThread|NativeThread|MainThread-UE4" "70"
}

log_i "[*] Game Optimization Daemon - Improving your experience™
Version: 0.1-r1

[$(date +%T)] [*] Game Optimization Logging started

[$(date +%T)] [*] Game Optimization Daemon enables you to get the best performance out of your favorite games.
"

echo "" >"$cpid"
(
while true; do
sleep 120
	pid="$(pgrep -f 'dts.freefireth|hotta.|.dw.h5yvzr.yt|GenshinImpact|cent.tmgp.cod|tmgp.pubgmhd|tencent.ig|pubg.imobile|tease.mrzhna|legendsmobilefps|ease.jddsaef|etease.g93na|ease.g93natw|ncent.tmgp.cf|legendsmobile|game.kwgt|obile.legends|tencent.lolm|league.wildrift|tmgp.sgame')"
	game="$(cat /proc/"$pid"/comm)"
	[[ ! "$pid" ]] && sleep 2
	[[ "$pid" != "$(cat "$cpid" | tail -n 1)" ]] && echo "$pid" >> "$cpid" && {
			log_g "$game found, optimizing..."
			echo "" >>"$glog"
			gameopt
			log_g "Optimization done"
			echo "" >>"$glog"
		} || continue
	done
) &