#!/system/bin/sh
# KTSR™ by pedro (pedrozzz0 @ GitHub)
# Thanks: tytydraco @ Github
# If you wanna use it as part of your project, please maintain the credits to it respective's author(s).

[[ "$1" == "--debug" ]] || [[ "$1" == "-d" ]] && set -x

modpath="/data/adb/modules/KTSR"

# Load libraries
source "$modpath/libs/libcommon.sh"

glog="/data/media/0/ktsr/game_opt.log"
cpid="/data/media/0/ktsr/pid"

log_g() {
	echo "[$(date +%T)]: [*] $1" >>"$glog"
}

log_i() { echo "$1" > "$glog"; }

gameopt() {
	rebuild_ps_cache
	pin_thread_on_perf "dts.freefire|league.wildrift|ncent.game.kwgt|tencent.lolm|league.wildrift|cent.tmgp.sgame|obile.legends|ncent.tmgp.cf|cent.tmgp.cod|o.GenshinImpact|game.allstar.eu|.game.kgth|lofduty.shooter|lebolt.standoff|flightsimulator|es.deadtrigger2|.carxtech.rally|DriftRacing|omin.protectors|om.sozap.badmen|erdog.tacticool|.netease.ddsfna|cade.next.mrglo|c.project_drift|headedshark.tco|amisu.driftmax2|.assolutoracing|garena.game.cod|ki.shadowfight3" "Apollo-Source|Apollo-File|UnityMain|UnityPreload"
	pin_thread_on_mid "dts.freefire|league.wildrift|ncent.game.kwgt|tencent.lolm|league.wildrift|cent.tmgp.sgame|obile.legends|ncent.tmgp.cf|cent.tmgp.cod|o.GenshinImpact|game.allstar.eu|.game.kgth|lofduty.shooter|lebolt.standoff|flightsimulator|es.deadtrigger2|.carxtech.rally|DriftRacing|omin.protectors|om.sozap.badmen|erdog.tacticool|.netease.ddsfna|cade.next.mrglo|c.project_drift|headedshark.tco|amisu.driftmax2|.assolutoracing|garena.game.cod|ki.shadowfight3" "NativeThread|Thread-|UnityGfxDeviceW|UnityMultiRende|ReadManager|UnityChoreograp|Worker Thread"
	pin_thread_on_pwr "dts.freefire|league.wildrift|ncent.game.kwgt|tencent.lolm|league.wildrift|cent.tmgp.sgame|obile.legends|ncent.tmgp.cf|cent.tmgp.cod|o.GenshinImpact|game.allstar.eu|.game.kgth|lofduty.shooter|xlebolt.standoff|cell.brawlstars|touchgames.dls|flightsimulator|ent.criticalops|td.modernstrike|es.deadtrigger2|.carxtech.rally|DriftRacing|omin.protectors|om.sozap.badmen|erdog.tacticool|.netease.ddsfna|cade.next.mrglo|c.project_drift|headedshark.tco|amisu.driftmax2|nt.tmgp.pubgmhd|com.tencent.ig|.netease.jddsaef|m.netease.g93na|netease.g93natw|egendsmobilefps|.legendsmobile|om.pubg.imobile|netease.mrzhna|hotta.|dw.h5yvzr.yt|n.c1game.naslim|.assolutoracing|garena.game.cod|squareenix.lis|walkingdead|ki.shadowfight3" "Audio|MIHOYO_NETWORK|tp_schedule|NDK Media|GVoice|FMOD mixer|FMOD stream|ff_read"
	pin_thread_on_perf "nt.tmgp.pubgmhd|com.tencent.ig|.netease.jddsaef|m.netease.g93na|netease.g93natw|egendsmobilefps|.legendsmobile|om.pubg.imobile|netease.mrzhna|hotta.|dw.h5yvzr.yt|m.roblox.client|cell.brawlstars|touchgames.dls|ent.criticalops|td.modernstrike|n.c1game.naslim|squareenix.lis|walkingdead" "Thread-|GLThread|SDLThread"
	pin_thread_on_mid "nt.tmgp.pubgmhd|com.tencent.ig|.netease.jddsaef|m.netease.g93na|netease.g93natw|egendsmobilefps|.legendsmobile|om.pubg.imobile|netease.mrzhna|hotta.|dw.h5yvzr.yt|m.roblox.client|cell.brawlstars|touchgames.dls|ent.criticalops|td.modernstrike|n.c1game.naslim|squareenix.lis|walkingdead" "RenderThread|TaskGraphNP|RHIThread|NativeThread|MainThread-UE4"
}

log_i "[*] Game Optimization Daemon - Improving your experience™
Version: 0.6-r1

[$(date +%T)] [*] Game Optimization Logging started

[$(date +%T)] [*] Game Optimization Daemon enables you to get the best performance out of your favorite games.
"

echo "" >"$cpid"
(
while true; do
sleep 120
	pid="$(pgrep -f 'dts.freefire|squareenix.lis|ki.shadowfight3|walkingdead|garena.game.codm|headedshark.tco|amisu.driftmax2|.assolutoracing|n.c1game.naslim|td.modernstrike|es.deadtrigger2|cade.next.mrglo|.netease.ddsfna|.carxtech.rally|DriftRacing|omin.protectors|om.sozap.badmen|erdog.tacticool|touchgames.dls|ent.criticalops|flightsimulator|league.wildrift|ncent.game.kwgt|tencent.lolm|league.wildrift|cent.tmgp.sgame|obile.legends|ncent.tmgp.cf|cent.tmgp.cod|o.GenshinImpact|game.allstar.eu|.game.kgth|lofduty.shooter|lebolt.standoff|nt.tmgp.pubgmhd|com.tencent.ig|.netease.jddsaef|m.netease.g93na|netease.g93natw|egendsmobilefps|.legendsmobile|om.pubg.imobile|netease.mrzhna|hotta.|dw.h5yvzr.yt|m.roblox.client|cell.brawlstars')"
	[[ ! "$pid" ]] && sleep 2
	[[ "$pid" != "$(grep -E '[0-9]' "$cpid" | tail -1)" ]] && [[ ! "$pid" == "" ]] && echo "$pid" >> "$cpid" && {
			game="$(cat /proc/"$pid"/comm)"
			log_g "$game found, optimizing..."
			echo "" >>"$glog"
			gameopt
			log_g "Optimization done"
			echo "" >>"$glog"
		} || continue
	done
) &